task1[Ксения Половченя]
mipt-diht/mipt-latex-fall2018-ksushapolo pull request #1
Opened 2018-10-24 15:14 UTC by ksushapolo

2018-10-24 16:07 UTC, AShepelevv requested changes

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +
Нет смысла писать `\par` и пропускать строчку. Если хочется отделить логически части текста – пусть, но тогда `\par` можно убрать.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	А теперь формулы. {\scshape Формула}~---краткое и точное словесное выражение, определение или же ряд математических величин, выраженный условными знаками.
После тире **всегда** ставится пробел.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\vspace{28 pt}
`\hspace{}` и `\vspace{}` лучше писать в том порядке, в котором они интуитивно должны работать (наоборот от того, что сейчас). А еще `\hspace{}` рекомендуется писать на той же строчке, что и последующий текст, горизонтального отступа которого мы и добиваемся.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	Уравнение Менделеева--Клайперона~---уравнение состояния идеального газа, имеющее вид $pV = \nu RT$, где $p$~---давление,  $V$~---объём, занимаемый газом, $T$~---температура газа, а $R$~---универсаль
После тире нужен пробел

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\vspace{28 pt}
см. комментарий выше

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
Перед `\ldots` не нужен пробел. Многоточие вплотную примыкает к тексту.
Давай попробуем избавиться от абзацного отступа без использования окружений.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	Для {\slshape плоского} треугольника со сторонами $a$, $b$ и $c$ и углом $\alpha$, лежащим против стороны $a$, справедливо соотношение $$a^2 = b^2 + c^2 - 2bccos\alpha,$$ из которого можно выразить
Косинус – это оператор. Сейчас у тебя просто произведение c на o и на s. Еще было бы не плохо знаки арифметических операция выделять пробелами и не писать переменные подряд, а разделять их пробелами.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	Для {\slshape плоского} треугольника со сторонами $a$, $b$ и $c$ и углом $\alpha$, лежащим против стороны $a$, справедливо соотношение $$a^2 = b^2 + c^2 - 2bccos\alpha,$$ из которого можно выразить
Выключенные (из текста) формулы желательно писать с новой строки.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	Пусть $p$~---полупериметр треугольника, тогда путём преобразований можно получить, что $$\tg\frac{\alpha}{2} = \sqrt{\frac{(p - b)(p - c)}{p(p - a)}},$$
После тире пробел. Выключенные (из текста) формулы желательно писать с новой строки.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	Это мой первый документ в системе компьютерной вёрстки \LaTeX.
Это строчка должна начинаться с абзацного отступа, выравнивания по центру там нет.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\hspace{20 pt}
В данный момент этот `\hspace{}` не работает вообще.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	{\itshape Audi multa,\\ loquere pauca}
Добавляй табуляцию для вложенных конструкций.

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\hspace{20 pt}
Что делает этот горизонтальный отступ?

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\hspace{15 pt}
А этот?

2018-10-24 16:07 UTC, AShepelevv commented on task1.tex
> +	\vspace{28 pt}
И единицы измерения лучше слитно писать.

2018-10-24 16:36 UTC, ksushapolo commented on task1.tex
> +	\hspace{15 pt}
Я просто перепутала операторы \hspace и \vspace.

2018-10-24 20:52 UTC, AShepelevv requested changes

2018-10-24 20:52 UTC, AShepelevv commented on task1.tex
> +	Для {\slshape плоского} треугольника со сторонами $a$, $b$ и $c$ и углом $\alpha$, лежащим против стороны $a$, справедливо соотношение $$a^2 = b^2 + c^2 - 2bccos\alpha,$$ из которого можно выразить
Видимо, пропустила?

2018-10-24 20:52 UTC, AShepelevv commented on task1.tex
> +	Пусть $p$~---полупериметр треугольника, тогда путём преобразований можно получить, что $$\tg\frac{\alpha}{2} = \sqrt{\frac{(p - b)(p - c)}{p(p - a)}},$$
И тут еще есть

2018-10-24 20:52 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
И тут

2018-10-24 20:52 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
Пробел все еще не нужен

2018-10-24 20:52 UTC, AShepelevv commented on task1.tex
> +	\vspace{20pt}
Этот вертикальный отступ не нужен.

2018-10-25 07:17 UTC, AShepelevv requested changes

2018-10-25 07:17 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
Пробел перед  `\ldots` все еще не нужен

2018-10-25 07:17 UTC, AShepelevv commented on task1.tex
> +	Это мой первый документ в системе компьютерной вёрстки \LaTeX.
Повторюсь: это строчка должна начинаться с абзацного отступа,

2018-10-25 07:17 UTC, AShepelevv commented on task1.tex
> +	Для {\slshape плоского} треугольника со сторонами $a$, $b$ и $c$ и углом $\alpha$, лежащим против стороны $a$, справедливо соотношение $$a^2 = b^2 + c^2 - 2bccos\alpha,$$ из которого можно выразить
КОСИНУС!

2018-10-25 07:17 UTC, AShepelevv commented on task1.tex
> +	\end{flushleft}
И избавлять от абзацного отступа нужно не окружением.

2018-10-25 10:26 UTC, AShepelevv requested changes

2018-10-25 10:26 UTC, AShepelevv commented on task1.tex
> +	\hspace{0pt} На сегодня, пожалуй, хватит\ldots Удачи!
Маленький горизонтальный отступ все равно остался...

2018-10-25 10:33 UTC, AShepelevv requested changes

2018-10-25 10:33 UTC, AShepelevv commented on task1.tex
> +	\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
Дело было не в этом пробеле. Такой же отступ все равно остался. Вспомни, что такое перевод строки

2018-10-25 14:11 UTC, AShepelevv requested changes

2018-10-25 14:11 UTC, AShepelevv commented on task1.tex
> +	\vspace{1cm}\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
Но таким образом в pdf нет вертикального отступа(

2018-10-25 14:29 UTC, ksushapolo commented on task1.tex
> +	\vspace{1cm}\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
Я не знаю, как это сделать(((

2018-10-25 14:43 UTC, AShepelevv commented on task1.tex
> +	\vspace{1cm}\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
```tex
$$\\[1cm]
На сегодня,\ldots
```

2018-10-25 14:43 UTC, AShepelevv commented on task1.tex
> +	\vspace{1cm}\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
@ksushapolo

2018-10-25 15:09 UTC, AShepelevv approved these changes

2018-10-25 15:09 UTC, AShepelevv commented on task1.tex
> +	\\[1cm]\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
Лиза подсказала?

2018-10-25 15:09 UTC, AShepelevv commented on task1.tex
> +	\\[1cm]\hspace{0pt}На сегодня, пожалуй, хватит\ldots Удачи!
Тогда уж `\hspace` зачем?

2018-10-25 15:09 UTC, merged